### ISSUE TITLE
Catalog Display

### ISSUE THREAD

**Issue by cameronRomo** [cameronRomo/depot#1]
### Tasks:
- [x] Add a store controller for customers to interact with products
- [x] Display products to the customer
- [x] Add page layout
  - [x] Navigation bar
  - [x] Banner
- [ ] Add tests
