### ISSUE TITLE
Add Catalog Display

### ISSUE THREAD

**Issue by cameronRomo** [cameronRomo/depot#2]
### Tasks:
- [x] Add a view to display the list of products
- [x] Cache products to account for large number of requrests
- [x] Add a layout with header and nav bar to navigate the app
- [x] Format pricing as currency instead of a number
