### ISSUE TITLE
Cart Creation

### ISSUE THREAD

**Issue by cameronRomo** [cameronRomo/depot#4]
### Tasks:
- [x] Assign a cart to a ~~user~~ session
- [x] Associate products to a cart
- [x] Add a button to add products to a cart
- [x] Display items in cart as multiples rather than sequentially
- [x] Rescue errors for when a cart is not found
  - [x] Display message to user
  - [x] log error
- [x] Add ability to delete cart
- [x] Redirect to store if a cart is deleted
- [x] Change from a `<ul>` to a `<table>`

**Comment by cameronRomo** [comment]
Changed from assigning a cart to a user to using the session cookie instead.

**Comment by cameronRomo** [comment]
Added more tasks after code review starting with displaying line items as multiples.
