### ISSUE TITLE
Upgrade Cart

### ISSUE THREAD

**Issue by cameronRomo** [cameronRomo/depot#5]
### Tasks:
- [x] Add quantity to the line_items model
- [x] Add the price of each line_item to the view, and a sum of all line items.
- [x] Display to the user
