### ISSUE TITLE
Hotwire the Storefront and the Cart

### ISSUE THREAD

**Issue by cameronRomo** [cameronRomo/depot#6]
### Tasks:
- [x] Move cart to storefront page
  - [x] Position inside sidebar
- [x] Hotwire the cart using Turbo methods
- [x] Highlight changes when adding line items to the cart
- [x] Broadcast pricing updates in the storefront
  - [x] Use ActionCable and WebSockets to update in real-time
    - [x] Create a channel
    - [x] Broadcast new price
    - [x] Recieve new price
