### ISSUE TITLE
Hotwire Cart

### ISSUE THREAD

**Issue by cameronRomo** [cameronRomo/depot#8]
### Tasks:
- [ ] Move the shopping cart into the sidebar
- [ ] Add Turbo Streams to LineItems `#create`
- [ ] Use ERB partials to return portions of page that need to be live updated
- [ ] Use TurboFrames to update the catalog display whenever a product changes
